name: CI
on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
env:
    NODE_VERSION: 20.x
jobs:
    typecheck:
        name: Check types
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
            - run: npm install
            - run: npm run typecheck
    lint:
        name: Lint code with ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
            - run: npm install
            - run: npm run lint
    check-formatting:
        name: Check code formatting with Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
            - run: npm install
            - run: npm run check-formatting
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
            - run: npm install
            - run: npm run test
    build:
        name: Build project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
            - run: npm install
            - run: npm run test
